import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Sidebar } from "components/molecules/Sidebar";
import { Header } from "components/molecules/Header";
import { AppContextProvider } from "contexts/AppContext";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <div className="fade-in flex">
            <div className="flex w-full flex-col">
              <Sidebar />
              <Header />
              <main className="fade-in min-h-[calc(100vh-89px)] bg-light-grey p-6 peer-[.w-72]/sidebar:pl-[19.5rem] dark:bg-very-dark-grey">
                {children}
              </main>
            </div>
            {modal}
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
