import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Sidebar } from "components/molecules/Sidebar";
import { Header } from "components/molecules/Header";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="flex min-h-screen">
            <Sidebar />
          </div>
          <div className="flex w-full flex-col">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
